import { StyleSheet } from 'react-native';
import { Spacing, Typography } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.four,
    borderBottomWidth: 1,
  },
  title: { fontSize: 24, fontWeight: '700' },
  scrollContent: { padding: Spacing.four, gap: Spacing.six, paddingBottom: Spacing.six * 2 },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: Spacing.four },

  // MODAL STYLES
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
  },
  modalCard: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 24,
    padding: 0,
    borderWidth: 1,
    boxShadow: '0px 10px 20px rgba(0, 0, 0, 0.1)',
    overflow: 'hidden',
  },
  closeButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 10,
    padding: 4,
  },
  modalContent: {
    padding: Spacing.six,
    alignItems: 'center',
    gap: 16,
  },
  heroIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: 'rgba(37, 99, 235, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  modalTitleContainer: {
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  heroSubTitle: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.bold,
  },
  modalMainTitle: {
    fontSize: 18,
    fontFamily: Typography.fontFamily.bold,
    textAlign: 'center',
  },
  modalDesc: {
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 12,
  },
  heroButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  heroButtonText: {
    color: '#fff',
    fontFamily: Typography.fontFamily.bold,
    fontSize: 15,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 8,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
  },
  checkboxLabel: {
    fontSize: 12,
  },

  // DATA SOURCE TOGGLE
  dataSourceContainer: {
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
  },
  dataSourceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dataSourceTitle: {
    fontSize: 13,
    fontFamily: Typography.fontFamily.bold,
  },
  toggleWrap: {
    flexDirection: 'row',
    borderRadius: 12,
    padding: 4,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBtnActive: {
    boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.1)',
  },
  toggleBtnText: {
    fontSize: 13,
    fontFamily: Typography.fontFamily.bold,
  },
  toggleBtnSubText: {
    fontSize: 10,
    opacity: 0.7,
    marginTop: 2,
  },

  // CONTEXT CARD (Current Profile)
  contextCard: {
    padding: Spacing.four,
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
  },
  contextHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  contextTitle: {
    fontSize: 14,
    fontFamily: Typography.fontFamily.bold,
  },
  contextGrid: {
    gap: 8,
  },
  contextItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    gap: 12,
  },
  contextItemIcon: {
    opacity: 0.8,
  },
  contextItemLabel: {
    fontSize: 11,
    opacity: 0.7,
  },
  contextItemValue: {
    fontSize: 14,
    fontFamily: Typography.fontFamily.bold,
    marginTop: 2,
  },

  // COMMON BUTTONS
  primaryButton: {
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  disabledButton: { opacity: 0.5 },
  primaryButtonText: { color: '#fff', fontFamily: Typography.fontFamily.bold, fontSize: 15 },

  // Upload Card (Custom Setup)
  uploadCard: {
    padding: Spacing.four,
    borderRadius: 16,
    gap: Spacing.four,
    borderWidth: 1,
  },
  uploadHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  uploadTitle: {
    fontSize: 15,
    fontFamily: Typography.fontFamily.bold,
  },
  uploadBody: { gap: 16 },
  currentCvBox: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  cvIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: 'rgba(37, 99, 235, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cvNameText: {
    fontSize: 15,
    fontFamily: Typography.fontFamily.bold,
  },
  noCvText: { fontSize: 14, fontStyle: 'italic' },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 16,
  },
  uploadButtonText: { fontSize: 14, fontFamily: Typography.fontFamily.bold },

  // History Section
  historySection: { gap: 16, marginTop: 12, paddingBottom: 24 },
  historyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  historyTitle: { fontSize: 17, fontFamily: Typography.fontFamily.bold },
  historyCard: { borderRadius: 16, padding: 16, gap: 16, marginHorizontal: 2 },
  historyCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  nestedContextBox: { gap: 6 },
  nestedContextTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 2 },
  nestedContextLabel: { fontSize: 12, fontFamily: Typography.fontFamily.medium, color: '#6B7280' },
  nestedContextDate: { fontSize: 12, fontFamily: Typography.fontFamily.medium, color: '#6B7280' },
  historyContextTitle: { fontSize: 16, fontFamily: Typography.fontFamily.bold, color: '#111827', lineHeight: 24 },
  nestedContextIndustry: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  historyActions: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  btnSecondary: { paddingVertical: 12, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: '#E5E7EB', alignItems: 'center', justifyContent: 'center' },
  btnSecondaryText: { fontSize: 13, fontFamily: Typography.fontFamily.bold, color: '#111827' },
  btnPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  btnPrimaryText: { color: '#fff', fontSize: 13, fontFamily: Typography.fontFamily.bold },
  emptyHistory: { fontSize: 14, textAlign: 'center' },

  // PREMIUM STYLES
  dataSourceContainerPremium: {
    gap: 16,
  },
  dataSourceTitlePremium: {
    fontSize: 11,
    fontFamily: Typography.fontFamily.bold,
    letterSpacing: 1,
    marginLeft: 4,
  },
  toggleWrapPremium: {
    flexDirection: 'row',
    borderRadius: 24,
    padding: 4,
  },
  toggleBtnPremium: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBtnActivePremium: {
    boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.05)',
  },
  toggleBtnTextPremium: {
    fontSize: 13,
    fontFamily: Typography.fontFamily.semibold,
  },
  contextCardPremium: {
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
  },
  contextItemPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  contextIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contextItemLabelPremium: {
    fontSize: 12,
    color: '#6B7280',
  },
  contextItemValuePremium: {
    fontSize: 14,
    fontFamily: Typography.fontFamily.medium,
  },
  contextDivider: {
    height: 1,
    marginVertical: 16,
  },
  primaryButtonPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 32,
    backgroundColor: '#3730A3',
    boxShadow: '0px 8px 16px rgba(55, 48, 163, 0.3)',
    gap: 12,
  },
  primaryButtonTextPremium: {
    color: '#fff',
    fontFamily: Typography.fontFamily.bold,
    fontSize: 15,
  },
  buttonIconWrapPremium: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  disabledButtonPremium: {
    opacity: 0.5,
    boxShadow: 'none',
  },

  // PREMIUM MODAL STYLES
  modalOverlayPremium: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
  },
  modalCardPremium: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 32,
    padding: 0,
    borderWidth: 1,
    boxShadow: '0px 24px 32px rgba(0, 0, 0, 0.15)',
    overflow: 'hidden',
  },
  closeButtonPremium: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContentPremium: {
    padding: 32,
    alignItems: 'center',
    gap: 20,
  },
  heroIconWrapPremium: {
    width: 72,
    height: 72,
    borderRadius: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  modalTitleContainerPremium: {
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  heroSubTitlePremium: {
    fontSize: 11,
    letterSpacing: 1.2,
    fontFamily: Typography.fontFamily.bold,
  },
  modalMainTitlePremium: {
    fontSize: 22,
    fontFamily: Typography.fontFamily.bold,
    textAlign: 'center',
    lineHeight: 30,
  },
  modalDescPremium: {
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 8,
  },
  modalPrimaryButtonPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 100,
    gap: 10,
    width: '100%',
    boxShadow: '0px 8px 16px rgba(0, 0, 0, 0.15)',
  },
  modalPrimaryButtonTextPremium: {
    color: '#fff',
    fontFamily: Typography.fontFamily.semibold,
    fontSize: 15,
  },
  checkboxContainerPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    gap: 10,
  },
  customCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#9CA3AF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxLabelPremium: {
    fontSize: 13,
  },
  floatingNavContainer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  inlineNavContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 24,
    boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.04)',
  },
  miniPageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    gap: 4,
  },
  miniPageBtnText: {
    fontSize: 13,
    fontFamily: Typography.fontFamily.bold,
  },
  inlinePageIndicator: {
    fontSize: 13,
    fontFamily: Typography.fontFamily.bold,
  },
});
