import { StyleSheet } from 'react-native';
import { Spacing, Radius, Shadows } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.four,
    borderBottomWidth: 1,
  },
  backButton: { marginRight: Spacing.three },
  title: { fontSize: 20, fontWeight: '700' },
  scrollContent: { padding: Spacing.four, gap: Spacing.four },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
  },
  card: {
    borderRadius: Radius.lg,
    padding: Spacing.four,
    borderWidth: 1,
    ...Shadows.sm,
    gap: Spacing.two,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radius.sm,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  scenarioTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  scenarioSummary: {
    fontSize: 13,
    lineHeight: 18,
    opacity: 0.8,
  },
  contentBox: {
    padding: Spacing.three,
    borderRadius: Radius.md,
    marginTop: Spacing.one,
    gap: 6,
  },
  contentHeader: {
    fontSize: 13,
    fontWeight: '700',
  },
  contentText: {
    fontSize: 13,
    lineHeight: 19,
  },
  historyStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: Spacing.one,
  },
  statItem: {
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 12,
    opacity: 0.7,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '800',
    marginTop: 2,
  },
  textArea: {
    borderWidth: 1,
    borderRadius: Radius.md,
    padding: Spacing.three,
    height: 120,
    textAlignVertical: 'top',
    fontSize: 14,
  },
  actionRow: {
    flexDirection: 'row',
    gap: Spacing.two,
    marginTop: Spacing.one,
  },
  guidelinesBox: {
    padding: Spacing.three,
    borderRadius: Radius.md,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    gap: 4,
    marginTop: Spacing.two,
  },
  guidelinesTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0f172a',
  },
  guidelinesText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#475569',
  },
  micButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#64748B',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: Radius.md,
    gap: 6,
  },
  micButtonText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  submitButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    paddingVertical: 12,
  },
  submitButtonText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  disabledButton: { opacity: 0.5 },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: Spacing.four,
  },
  successRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  successText: {
    fontWeight: '700',
    fontSize: 15,
  },
  evaluationBox: {
    padding: Spacing.three,
    borderRadius: Radius.md,
  },
  evaluationText: {
    fontSize: 13,
    lineHeight: 18,
  },
  errorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  // Structured Evaluation Styles
  evalScoreHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
    padding: Spacing.three,
    borderRadius: Radius.md,
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  scoreGauge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#059669',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scoreGaugeText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '800',
  },
  scoreGaugeLabel: {
    color: '#d1fae5',
    fontSize: 10,
    fontWeight: '600',
  },
  evalScoreContent: {
    flex: 1,
    gap: 2,
  },
  evalScoreTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#065f46',
  },
  evalScoreFeedback: {
    fontSize: 12,
    lineHeight: 17,
    color: '#047857',
  },
  sectionHeading: {
    fontSize: 14,
    fontWeight: '700',
    marginTop: Spacing.two,
    marginBottom: Spacing.one,
  },
  dimensionCard: {
    padding: Spacing.three,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    gap: 4,
    marginBottom: Spacing.two,
  },
  dimensionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dimensionName: {
    fontSize: 13,
    fontWeight: '700',
    flex: 1,
  },
  dimensionBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: Radius.full,
  },
  dimensionBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  dimensionEvidence: {
    fontSize: 12,
    fontStyle: 'italic',
    color: '#475569',
    backgroundColor: '#ffffff',
    padding: Spacing.two,
    borderRadius: Radius.sm,
    borderLeftWidth: 3,
    borderLeftColor: '#cbd5e1',
    marginVertical: 4,
  },
  dimensionEvidenceBox: {
    padding: Spacing.two,
    borderRadius: Radius.sm,
    borderLeftWidth: 3,
    borderLeftColor: '#0d9488',
    backgroundColor: '#f8fafc',
    marginVertical: 4,
  },
  dimensionEvidenceText: {
    fontSize: 12,
    fontStyle: 'italic',
    color: '#334155',
    lineHeight: 17,
  },
  dimensionFeedbackText: {
    fontSize: 12,
    lineHeight: 17,
    color: '#334155',
  },
  strengthsCard: {
    padding: Spacing.three,
    borderRadius: Radius.md,
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#a7f3d0',
    gap: 6,
    marginBottom: Spacing.two,
  },
  gapsCard: {
    padding: Spacing.three,
    borderRadius: Radius.md,
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fde68a',
    gap: 6,
    marginBottom: Spacing.two,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  strengthsTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#047857',
  },
  gapsTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#b45309',
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  bulletText: {
    fontSize: 12,
    lineHeight: 17,
    flex: 1,
  },
  approachCard: {
    padding: Spacing.three,
    borderRadius: Radius.md,
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#bfdbfe',
    gap: 6,
    marginBottom: Spacing.two,
  },
  approachTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1d4ed8',
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  stepNum: {
    fontSize: 12,
    fontWeight: '800',
    color: '#2563eb',
  },
  stepText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#1e40af',
    flex: 1,
  },
  // History Item Rows
  historyItemRow: {
    padding: Spacing.three,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    gap: 8,
    marginBottom: Spacing.two,
  },
  historyItemRowSelected: {
    borderColor: '#3b82f6',
    backgroundColor: '#eff6ff',
  },
  historyItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyNum: {
    fontSize: 13,
    fontWeight: '700',
  },
  historyDate: {
    fontSize: 11,
    color: '#64748b',
  },
  historyActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  historyScoreText: {
    fontSize: 14,
    fontWeight: '800',
  },
  historyDeltaBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: Radius.sm,
  },
  historyDeltaText: {
    fontSize: 11,
    fontWeight: '700',
  },
  historyButtonSmall: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: Radius.sm,
    backgroundColor: '#f1f5f9',
  },
  historyButtonTextSmall: {
    fontSize: 11,
    fontWeight: '600',
    color: '#334155',
  },
  quoteBox: {
    padding: Spacing.two,
    borderRadius: Radius.sm,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginTop: 4,
  },
  quoteLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#64748b',
    marginBottom: 2,
  },
  quoteText: {
    fontSize: 12,
    lineHeight: 17,
    color: '#334155',
  },
});
