import { StyleSheet } from 'react-native';
import { Spacing, Radius, Shadows } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.four,
    borderBottomWidth: 1,
    gap: Spacing.two,
  },
  backButton: { marginRight: Spacing.two },
  title: { fontSize: 20, fontWeight: '700' },
  scrollContent: { padding: Spacing.four, gap: Spacing.four },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
  },
  card: {
    borderRadius: Radius.lg,
    padding: Spacing.four,
    borderWidth: 1,
    ...Shadows.sm,
    gap: Spacing.two,
  },
  scoreBadge: {
    flexDirection: 'row',
    alignItems: 'baseline',
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.two,
    borderRadius: Radius.full,
    marginBottom: Spacing.two,
  },
  scoreNumber: {
    fontSize: 42,
    fontWeight: '800',
  },
  scoreMax: {
    fontSize: 16,
    fontWeight: '600',
    opacity: 0.7,
    marginLeft: 4,
  },
  scoreTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  disclaimerText: {
    fontSize: 12,
    textAlign: 'center',
    opacity: 0.6,
    fontStyle: 'italic',
    marginTop: 4,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: '700',
  },
  questionReviewHeader: {
    flexDirection: 'row',
    gap: Spacing.two,
    marginBottom: 4,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radius.sm,
  },
  badgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  questionTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  answerBox: {
    padding: Spacing.three,
    borderRadius: Radius.md,
  },
  answerText: {
    fontSize: 13,
    lineHeight: 18,
  },
  subTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginTop: 4,
  },
  rubricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  rubricLabel: { fontSize: 13, opacity: 0.8 },
  rubricScore: { fontSize: 13, fontWeight: '700' },
  bodyText: { fontSize: 13, lineHeight: 18, opacity: 0.9 },
  bulletText: { fontSize: 13, lineHeight: 18 },
  suggestedBox: {
    padding: Spacing.three,
    borderRadius: Radius.md,
    marginTop: Spacing.one,
    gap: 4,
  },
  primaryButton: {
    borderRadius: Radius.md,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: Spacing.two,
    ...Shadows.md,
  },
  primaryButtonText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  secondaryButton: {
    borderRadius: Radius.md,
    paddingVertical: 10,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: Spacing.two,
  },
  secondaryButtonText: { fontWeight: '700', fontSize: 14 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
  },
  modalCard: {
    width: '100%',
    borderRadius: Radius.xl,
    padding: Spacing.five,
    borderWidth: 1,
    alignItems: 'center',
    gap: Spacing.two,
  },
  modalTitle: { fontSize: 18, fontWeight: '700', textAlign: 'center' },
  modalSub: { fontSize: 13, textAlign: 'center', opacity: 0.8 },
  reasonOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.three,
    borderRadius: Radius.md,
    borderWidth: 1,
    gap: Spacing.two,
  },
  reasonOptionText: { fontSize: 13 },
});
